#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Biaticos")]
	public partial class DB_ViaticosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DB_ViaticosDataContext() : 
				base(global::DAL.Properties.Settings.Default.DB_BiaticosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ViaticosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ViaticosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ViaticosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ViaticosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarPersona")]
		public int sp_ActualizarPersona([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomUsuario", DbType="NVarChar(30)")] string nomUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerApellido", DbType="NVarChar(125)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoApellido", DbType="NVarChar(125)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(125)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nomUsuario, nombre, primerApellido, segundoApellido, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarUsuario")]
		public int sp_ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomUsuario", DbType="NVarChar(30)")] string nomUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstado", DbType="Int")] System.Nullable<int> idEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClaveAcceso", DbType="NVarChar(30)")] string claveAcceso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nomUsuario, idRol, idEstado, claveAcceso);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerUsuario")]
		public ISingleResult<sp_ObtenerUsuarioResult> sp_ObtenerUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomUsuario", DbType="NVarChar(30)")] string nomUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nomUsuario);
			return ((ISingleResult<sp_ObtenerUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_RegistrarPersona")]
		public int sp_RegistrarPersona([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPersona", DbType="Int")] System.Nullable<int> idPersona, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomUsuario", DbType="NVarChar(30)")] string nomUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerApellido", DbType="NVarChar(125)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoApellido", DbType="NVarChar(125)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(125)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPersona, nomUsuario, nombre, primerApellido, segundoApellido, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_RegistrarUsuario")]
		public int sp_RegistrarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomUsuario", DbType="NVarChar(30)")] string nomUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClaveAcceso", DbType="NVarChar(30)")] string claveAcceso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nomUsuario, idRol, claveAcceso);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ValidarCredenciales")]
		public ISingleResult<sp_ValidarCredencialesResult> sp_ValidarCredenciales([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomUsuario", DbType="NVarChar(30)")] string nomUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClaveAcceso", DbType="NVarChar(30)")] string claveAcceso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nomUsuario, claveAcceso);
			return ((ISingleResult<sp_ValidarCredencialesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerPersona")]
		public ISingleResult<sp_ObtenerPersonaResult> sp_ObtenerPersona([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NomUsuario", DbType="NVarChar(30)")] string nomUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nomUsuario);
			return ((ISingleResult<sp_ObtenerPersonaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerIDPersona")]
		public ISingleResult<sp_ObtenerIDPersonaResult> sp_ObtenerIDPersona([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPersona", DbType="Int")] System.Nullable<int> idPersona)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPersona);
			return ((ISingleResult<sp_ObtenerIDPersonaResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_ObtenerUsuarioResult
	{
		
		private string _NomUsuario;
		
		private string _ClaveAcceso;
		
		private int _IdRol;
		
		private int _IdEstado;
		
		public sp_ObtenerUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomUsuario", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string NomUsuario
		{
			get
			{
				return this._NomUsuario;
			}
			set
			{
				if ((this._NomUsuario != value))
				{
					this._NomUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveAcceso", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ClaveAcceso
		{
			get
			{
				return this._ClaveAcceso;
			}
			set
			{
				if ((this._ClaveAcceso != value))
				{
					this._ClaveAcceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL")]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
	}
	
	public partial class sp_ValidarCredencialesResult
	{
		
		private string _NomUsuario;
		
		public sp_ValidarCredencialesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomUsuario", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string NomUsuario
		{
			get
			{
				return this._NomUsuario;
			}
			set
			{
				if ((this._NomUsuario != value))
				{
					this._NomUsuario = value;
				}
			}
		}
	}
	
	public partial class sp_ObtenerPersonaResult
	{
		
		private int _IdPersona;
		
		private string _Nombre;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private string _Email;
		
		public sp_ObtenerPersonaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="Int NOT NULL")]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					this._IdPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(125) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="NVarChar(125) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this._PrimerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="NVarChar(125)")]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this._SegundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(125)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class sp_ObtenerIDPersonaResult
	{
		
		private int _IdPersona;
		
		public sp_ObtenerIDPersonaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPersona", DbType="Int NOT NULL")]
		public int IdPersona
		{
			get
			{
				return this._IdPersona;
			}
			set
			{
				if ((this._IdPersona != value))
				{
					this._IdPersona = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
