<?xml version="1.0" encoding="utf-8"?><Database Name="DB_Biaticos" Class="DB_ViaticosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2CJA1P6\SQLEXPRESS;Initial Catalog=DB_Biaticos;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="DB_BiaticosConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_ActualizarPersona" Method="sp_ActualizarPersona">
    <Parameter Name="NomUsuario" Parameter="nomUsuario" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="PrimerApellido" Parameter="primerApellido" Type="System.String" DbType="NVarChar(125)" />
    <Parameter Name="SegundoApellido" Parameter="segundoApellido" Type="System.String" DbType="NVarChar(125)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(125)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ActualizarUsuario" Method="sp_ActualizarUsuario">
    <Parameter Name="NomUsuario" Parameter="nomUsuario" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="IdRol" Parameter="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdEstado" Parameter="idEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClaveAcceso" Parameter="claveAcceso" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ObtenerUsuario" Method="sp_ObtenerUsuario">
    <Parameter Name="NomUsuario" Parameter="nomUsuario" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="sp_ObtenerUsuarioResult">
      <Column Name="NomUsuario" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ClaveAcceso" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="IdRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_RegistrarPersona" Method="sp_RegistrarPersona">
    <Parameter Name="IdPersona" Parameter="idPersona" Type="System.Int32" DbType="Int" />
    <Parameter Name="NomUsuario" Parameter="nomUsuario" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="PrimerApellido" Parameter="primerApellido" Type="System.String" DbType="NVarChar(125)" />
    <Parameter Name="SegundoApellido" Parameter="segundoApellido" Type="System.String" DbType="NVarChar(125)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(125)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RegistrarUsuario" Method="sp_RegistrarUsuario">
    <Parameter Name="NomUsuario" Parameter="nomUsuario" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="IdRol" Parameter="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClaveAcceso" Parameter="claveAcceso" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ValidarCredenciales" Method="sp_ValidarCredenciales">
    <Parameter Name="NomUsuario" Parameter="nomUsuario" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="ClaveAcceso" Parameter="claveAcceso" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="sp_ValidarCredencialesResult">
      <Column Name="NomUsuario" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ObtenerPersona" Method="sp_ObtenerPersona">
    <Parameter Name="NomUsuario" Parameter="nomUsuario" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="sp_ObtenerPersonaResult">
      <Column Name="IdPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="PrimerApellido" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="SegundoApellido" Type="System.String" DbType="NVarChar(125)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(125)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ObtenerIDPersona" Method="sp_ObtenerIDPersona">
    <Parameter Name="IdPersona" Parameter="idPersona" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ObtenerIDPersonaResult">
      <Column Name="IdPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>